### ISSUE TITLE
can't validate proj.win10 package

### ISSUE THREAD

**Issue by tienthanh1993** [Microsoft/cocos2d-x#192]
i tried to pack and upload to window phone store but when validate package it give me these error 

```
API OpenSemaphore in api-ms-win-core-synch-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API CreateSemaphore in api-ms-win-core-kernel32-legacy-l1-1-0.dll is not supported for this application type. System.Threading.dll calls this API.
API ExecuteAssembly in uwphost.dll is not supported for this application type. UWPShim.exe calls this API.
API DllGetActivationFactory in uwphost.dll is not supported for this application type. UWPShim.exe has an export that forwards to this API.
```

**Comment by stammen** [comment]
It looks like this may be related to:

https://social.msdn.microsoft.com/Forums/en-US/3e559d65-19cb-49a0-a9cc-a62de045dd87/rtm-known-issue-my-uwp-application-fails-wack-compliance-testing-with-output-saying-im-using-apis?forum=Win10SDKToolsIssues

**Comment by tienthanh1993** [comment]
thank you stammen!
i switched to release mode, it's gone.
